### ISSUE TITLE
I cant find modules-3.1.10-tk*.tar.gz

### ISSUE THREAD

**Issue by artefactop** [kulve/tegra-debian#2]
I don't know from where you get the modules, Could you explain it?

**Comment by kulve** [comment]
You can get the modules from the URL stated in my blog post. You can also compile them yourself, if you know what you are doing.

For compiling the kernel you need a proper toolchain after which you can compile the kernel and the modules:

make ARCH=arm CROSS_COMPILE=/path/to/toolchain/bin/arm-none-eabi- INSTALL_MOD_PATH=/tmp/ouya zImage modules_install
